// Module included in the following assemblies:
//
// * installing/installing_aws/installing-aws-network-customizations.adoc
// * installing/installing_azure/installing-azure-network-customizations.adoc
// * installing/installing_bare_metal/installing-bare-metal-network-customizations.adoc
// * installing/installing_vsphere/installing-vsphere-network-customizations.adoc
// * installing/installing_gcp/installing-gcp-network-customizations.adoc
// * installing/installing_vsphere/installing-vsphere-installer-provisioned-network-customizations.adoc

ifeval::["{context}" == "installing-bare-metal-network-customizations"]
:ignition-config:
endif::[]
ifeval::["{context}" == "installing-vsphere-network-customizations"]
:ignition-config:
:vsphere:
endif::[]

[id="modifying-nwoperator-config-startup_{context}"]
= Ensuring networking components only run on the control plane

You can configure networking components to only run on the control plane before you
install the cluster. [insert detailed description].

[IMPORTANT]
====
Modifying the {product-title} manifest files directly is not supported.
====

.Prerequisites

* Create the `install-config.yaml` file and complete any modifications to it.
ifdef::ignition-config[]
* Create the Ignition config files for your cluster.
endif::ignition-config[]

.Procedure

. Change to the directory that contains the installation program and create the manifests:
+
[source,terminal]
----
$ ./openshift-install create manifests --dir=<installation_directory> <1>
----
<1> For `<installation_directory>`, specify the name of the directory that
contains the `install-config.yaml` file for your cluster.

. Create a file that is named `cluster-network-99-config.yml` in the
`<installation_directory>/manifests/` directory:
+
[source,terminal]
----
$ touch <installation_directory>/manifests/cluster-network-99-config.yml <1>
----
<1> For `<installation_directory>`, specify the directory name that contains the
`manifests/` directory for your cluster.
+
After creating the file, several network configuration files are in the
`manifests/` directory, as shown:
+
[source,terminal]
----
$ ls <installation_directory>/manifests/cluster-network-*
----
+
.Example output
[source,terminal]
----
cluster-network-01-crd.yml
cluster-network-02-config.yml
cluster-network-99-config.yml
----

. Open the `cluster-network-99-config.yml` file in an editor and enter a custom resource (CR) that
describes the Operator configuration you want:
+
[source,yaml]
----
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 50-worker-fix-ipi-rwn
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.1.0
    systemd:
      units:
      - name: nodeip-configuration.service
        enabled: true
        contents: |
          [Unit]
          Description=Writes IP address configuration so that kubelet and crio services select a valid node IP
          Wants=network-online.target
          After=network-online.target ignition-firstboot-complete.service
          Before=kubelet.service crio.service
          [Service]
          Type=oneshot
          ExecStart=/bin/bash -c "exit 0 "
          [Install]
          WantedBy=multi-user.target
    storage:
      files:
        - contents:
            source: data:,
            verification: {}
          filesystem: root
          mode: 420
          path: /etc/kubernetes/manifests/keepalived.yaml
        - contents:
            source: data:,
            verification: {}
          filesystem: root
          mode: 420
          path: /etc/kubernetes/manifests/mdns-publisher.yaml
        - contents:
            source: data:,
            verification: {}
          filesystem: root
          mode: 420
          path: /etc/kubernetes/manifests/coredns.yaml
---
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
spec:
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/master: ""
----
+
[insert description of the changes]

. Save the `cluster-network-03-config.yml` file and quit the text editor.
. Optional: Back up the `manifests/cluster-network-03-config.yml` file. The
installation program deletes the `manifests/` directory when creating the
cluster.

ifdef::vsphere[]
. Remove the Kubernetes manifest files that define the control plane machines and compute machineSets:
+
[source,terminal]
----
$ rm -f openshift/99_openshift-cluster-api_master-machines-*.yaml openshift/99_openshift-cluster-api_worker-machineset-*.yaml
----
+
Because you create and manage these resources yourself, you do not have
to initialize them.
+
* You can preserve the MachineSet files to create compute machines by using the machine API, but you must update references to them to match your environment.
endif::vsphere[]

ifeval::["{context}" == "installing-bare-metal-network-customizations"]
:!ignition-config:
endif::[]
ifeval::["{context}" == "installing-vsphere-network-customizations"]
:!ignition-config:
:!vsphere:
endif::[]
